name: Build CODE_INDEX
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: Branch to index (e.g., flatten-tree)
        required: true
        default: flatten-tree

permissions:
  contents: write

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # stay on main; we'll fetch the target separately

      - name: Fetch target branch
        run: |
          git fetch origin ${{ inputs.target_branch }}

      - name: Generate CODE_INDEX.md on main with links to target branch
        run: |
          echo "# Code Index (${{ inputs.target_branch }})" > CODE_INDEX.md
          echo "" >> CODE_INDEX.md
          git ls-tree -r --name-only origin/${{ inputs.target_branch }} \
            | grep '^ResoWave/.*\.swift$' | sort | while read -r f; do
              echo "- [$f](https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${{ inputs.target_branch }}/${f})" >> CODE_INDEX.md
            done

      - name: Commit and push to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CODE_INDEX.md
          git commit -m "Add/Update CODE_INDEX for ${{ inputs.target_branch }}" || echo "No changes"
          git push
